name: Run tests with dispatch

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository which triggered workflow'
        required: true
        default: 'unknownRepository'
      run_id:
        description: 'check run id'
        required: true
        default: 'unknownId'
      branch:
        description: 'Branch in repository'
        required: true
        default: 'unknownBranch'
      sha:
        description: 'SHA'
        required: true
        default: 'sha'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: showing inputs
        id: test
        run: |
          echo Repo is ${{ github.event.inputs.repo }}
          echo run_id is ${{ github.event.inputs.run_id }}
          echo branch is ${{ github.event.inputs.branch }}

      - name: pending for ${{ github.event.inputs.branch }} at ${{ github.event.inputs.repo }} repo
        uses: percona-platform/github-status-action@v1
        with:
          authToken: ${{secrets.ROBOT_TOKEN}}
          context: 'UI tests'
          description: 'Test execution has been started'
          state: 'pending'
          repository: ${{ github.event.inputs.repo }}
          target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          sha: ${{ github.event.inputs.sha }}

      - name: pending for ${{ github.event.inputs.branch }} at ${{ github.event.inputs.repo }} repo
        uses: percona-platform/github-status-action@v1
        with:
          authToken: ${{secrets.ROBOT_TOKEN}}
          context: 'API tests'
          description: 'API Test execution has been started'
          state: 'pending'
          repository: ${{ github.event.inputs.repo }}
          target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          sha: ${{ github.event.inputs.sha }}

      - name: Sleep
        run: sleep 1m

      - name: Success for API tests
        uses: percona-platform/github-status-action@v1
        with:
          authToken: ${{secrets.ROBOT_TOKEN}}
          context: 'API tests'
          description: 'API Test execution succeeded'
          state: 'success'
          repository: ${{ github.event.inputs.repo }}
          target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          sha: ${{ github.event.inputs.sha }}


      - name: Success for tests
        uses: percona-platform/github-status-action@v1
        with:
          authToken: ${{secrets.ROBOT_TOKEN}}
          context: 'UI tests'
          description: 'UI Test execution succeeded'
          state: 'success'
          repository: ${{ github.event.inputs.repo }}
          target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          sha: ${{ github.event.inputs.sha }}
